/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForMerchantsRouteImport } from './routes/for-merchants'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DealsIdRouteImport } from './routes/deals.$id'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AdminTrustRouteImport } from './routes/admin.trust'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AdminNotificationsDebugRouteImport } from './routes/admin.notifications.debug'
import { Route as AuthenticatedProfileStoreRouteImport } from './routes/_authenticated/profile.store'
import { Route as AuthenticatedProfileSecurityRouteImport } from './routes/_authenticated/profile.security'
import { Route as AuthenticatedProfileNotificationsRouteImport } from './routes/_authenticated/profile.notifications'
import { Route as AuthenticatedProfileDashboardRouteImport } from './routes/_authenticated/profile.dashboard'
import { Route as AuthenticatedProfileBillingRouteImport } from './routes/_authenticated/profile.billing'
import { Route as AuthenticatedProfileAnalyticsRouteImport } from './routes/_authenticated/profile.analytics'
import { Route as AuthenticatedProfileAdsIndexRouteImport } from './routes/_authenticated/profile.ads.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksNotifyDealRouteImport } from './routes/api/public/hooks/notify-deal'
import { Route as ApiPublicConfigMapsRouteImport } from './routes/api/public/config/maps'
import { Route as AuthenticatedProfileAdsNewRouteImport } from './routes/_authenticated/profile.ads.new'
import { Route as AuthenticatedProfileAdsIdRouteImport } from './routes/_authenticated/profile.ads.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForMerchantsRoute = ForMerchantsRouteImport.update({
  id: '/for-merchants',
  path: '/for-merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIdRoute = DealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrustRoute = AdminTrustRouteImport.update({
  id: '/admin/trust',
  path: '/admin/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/admin/deals',
  path: '/admin/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/admin/businesses',
  path: '/admin/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsDebugRoute = AdminNotificationsDebugRouteImport.update({
  id: '/admin/notifications/debug',
  path: '/admin/notifications/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileStoreRoute =
  AuthenticatedProfileStoreRouteImport.update({
    id: '/profile/store',
    path: '/profile/store',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileSecurityRoute =
  AuthenticatedProfileSecurityRouteImport.update({
    id: '/profile/security',
    path: '/profile/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileNotificationsRoute =
  AuthenticatedProfileNotificationsRouteImport.update({
    id: '/profile/notifications',
    path: '/profile/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileDashboardRoute =
  AuthenticatedProfileDashboardRouteImport.update({
    id: '/profile/dashboard',
    path: '/profile/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileBillingRoute =
  AuthenticatedProfileBillingRouteImport.update({
    id: '/profile/billing',
    path: '/profile/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileAnalyticsRoute =
  AuthenticatedProfileAnalyticsRouteImport.update({
    id: '/profile/analytics',
    path: '/profile/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileAdsIndexRoute =
  AuthenticatedProfileAdsIndexRouteImport.update({
    id: '/profile/ads/',
    path: '/profile/ads/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotifyDealRoute =
  ApiPublicHooksNotifyDealRouteImport.update({
    id: '/api/public/hooks/notify-deal',
    path: '/api/public/hooks/notify-deal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConfigMapsRoute = ApiPublicConfigMapsRouteImport.update({
  id: '/api/public/config/maps',
  path: '/api/public/config/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileAdsNewRoute =
  AuthenticatedProfileAdsNewRouteImport.update({
    id: '/profile/ads/new',
    path: '/profile/ads/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileAdsIdRoute =
  AuthenticatedProfileAdsIdRouteImport.update({
    id: '/profile/ads/$id',
    path: '/profile/ads/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/for-merchants': typeof ForMerchantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/nearby': typeof NearbyRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/deals/$id': typeof DealsIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/profile/analytics': typeof AuthenticatedProfileAnalyticsRoute
  '/profile/billing': typeof AuthenticatedProfileBillingRoute
  '/profile/dashboard': typeof AuthenticatedProfileDashboardRoute
  '/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/profile/security': typeof AuthenticatedProfileSecurityRoute
  '/profile/store': typeof AuthenticatedProfileStoreRoute
  '/admin/notifications/debug': typeof AdminNotificationsDebugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/profile/ads/$id': typeof AuthenticatedProfileAdsIdRoute
  '/profile/ads/new': typeof AuthenticatedProfileAdsNewRoute
  '/api/public/config/maps': typeof ApiPublicConfigMapsRoute
  '/api/public/hooks/notify-deal': typeof ApiPublicHooksNotifyDealRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/profile/ads/': typeof AuthenticatedProfileAdsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/for-merchants': typeof ForMerchantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/nearby': typeof NearbyRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/deals/$id': typeof DealsIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin': typeof AdminIndexRoute
  '/deals': typeof DealsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/profile/analytics': typeof AuthenticatedProfileAnalyticsRoute
  '/profile/billing': typeof AuthenticatedProfileBillingRoute
  '/profile/dashboard': typeof AuthenticatedProfileDashboardRoute
  '/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/profile/security': typeof AuthenticatedProfileSecurityRoute
  '/profile/store': typeof AuthenticatedProfileStoreRoute
  '/admin/notifications/debug': typeof AdminNotificationsDebugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/profile/ads/$id': typeof AuthenticatedProfileAdsIdRoute
  '/profile/ads/new': typeof AuthenticatedProfileAdsNewRoute
  '/api/public/config/maps': typeof ApiPublicConfigMapsRoute
  '/api/public/hooks/notify-deal': typeof ApiPublicHooksNotifyDealRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/profile/ads': typeof AuthenticatedProfileAdsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/for-merchants': typeof ForMerchantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/nearby': typeof NearbyRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/deals/$id': typeof DealsIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/deals/': typeof DealsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/_authenticated/profile/analytics': typeof AuthenticatedProfileAnalyticsRoute
  '/_authenticated/profile/billing': typeof AuthenticatedProfileBillingRoute
  '/_authenticated/profile/dashboard': typeof AuthenticatedProfileDashboardRoute
  '/_authenticated/profile/notifications': typeof AuthenticatedProfileNotificationsRoute
  '/_authenticated/profile/security': typeof AuthenticatedProfileSecurityRoute
  '/_authenticated/profile/store': typeof AuthenticatedProfileStoreRoute
  '/admin/notifications/debug': typeof AdminNotificationsDebugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/profile/ads/$id': typeof AuthenticatedProfileAdsIdRoute
  '/_authenticated/profile/ads/new': typeof AuthenticatedProfileAdsNewRoute
  '/api/public/config/maps': typeof ApiPublicConfigMapsRoute
  '/api/public/hooks/notify-deal': typeof ApiPublicHooksNotifyDealRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/profile/ads/': typeof AuthenticatedProfileAdsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/delete-account'
    | '/faq'
    | '/favorites'
    | '/for-merchants'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/nearby'
    | '/partner'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/select-role'
    | '/signup'
    | '/terms'
    | '/admin/banners'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/deals'
    | '/admin/trust'
    | '/categories/$slug'
    | '/deals/$id'
    | '/email/unsubscribe'
    | '/stores/$id'
    | '/admin/'
    | '/deals/'
    | '/stores/'
    | '/profile/analytics'
    | '/profile/billing'
    | '/profile/dashboard'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/store'
    | '/admin/notifications/debug'
    | '/lovable/email/suppression'
    | '/profile/ads/$id'
    | '/profile/ads/new'
    | '/api/public/config/maps'
    | '/api/public/hooks/notify-deal'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/profile/ads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/delete-account'
    | '/faq'
    | '/favorites'
    | '/for-merchants'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/nearby'
    | '/partner'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/select-role'
    | '/signup'
    | '/terms'
    | '/admin/banners'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/deals'
    | '/admin/trust'
    | '/categories/$slug'
    | '/deals/$id'
    | '/email/unsubscribe'
    | '/stores/$id'
    | '/admin'
    | '/deals'
    | '/stores'
    | '/profile/analytics'
    | '/profile/billing'
    | '/profile/dashboard'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/store'
    | '/admin/notifications/debug'
    | '/lovable/email/suppression'
    | '/profile/ads/$id'
    | '/profile/ads/new'
    | '/api/public/config/maps'
    | '/api/public/hooks/notify-deal'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/profile/ads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/delete-account'
    | '/faq'
    | '/favorites'
    | '/for-merchants'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/nearby'
    | '/partner'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/select-role'
    | '/signup'
    | '/terms'
    | '/admin/banners'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/deals'
    | '/admin/trust'
    | '/categories/$slug'
    | '/deals/$id'
    | '/email/unsubscribe'
    | '/stores/$id'
    | '/admin/'
    | '/deals/'
    | '/stores/'
    | '/_authenticated/profile/analytics'
    | '/_authenticated/profile/billing'
    | '/_authenticated/profile/dashboard'
    | '/_authenticated/profile/notifications'
    | '/_authenticated/profile/security'
    | '/_authenticated/profile/store'
    | '/admin/notifications/debug'
    | '/lovable/email/suppression'
    | '/_authenticated/profile/ads/$id'
    | '/_authenticated/profile/ads/new'
    | '/api/public/config/maps'
    | '/api/public/hooks/notify-deal'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/profile/ads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  ForMerchantsRoute: typeof ForMerchantsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NearbyRoute: typeof NearbyRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminTrustRoute: typeof AdminTrustRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DealsIdRoute: typeof DealsIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  StoresIdRoute: typeof StoresIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  AdminNotificationsDebugRoute: typeof AdminNotificationsDebugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicConfigMapsRoute: typeof ApiPublicConfigMapsRoute
  ApiPublicHooksNotifyDealRoute: typeof ApiPublicHooksNotifyDealRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-merchants': {
      id: '/for-merchants'
      path: '/for-merchants'
      fullPath: '/for-merchants'
      preLoaderRoute: typeof ForMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$id': {
      id: '/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof DealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trust': {
      id: '/admin/trust'
      path: '/admin/trust'
      fullPath: '/admin/trust'
      preLoaderRoute: typeof AdminTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/admin/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/admin/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications/debug': {
      id: '/admin/notifications/debug'
      path: '/admin/notifications/debug'
      fullPath: '/admin/notifications/debug'
      preLoaderRoute: typeof AdminNotificationsDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/store': {
      id: '/_authenticated/profile/store'
      path: '/profile/store'
      fullPath: '/profile/store'
      preLoaderRoute: typeof AuthenticatedProfileStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/security': {
      id: '/_authenticated/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AuthenticatedProfileSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/notifications': {
      id: '/_authenticated/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof AuthenticatedProfileNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/dashboard': {
      id: '/_authenticated/profile/dashboard'
      path: '/profile/dashboard'
      fullPath: '/profile/dashboard'
      preLoaderRoute: typeof AuthenticatedProfileDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/billing': {
      id: '/_authenticated/profile/billing'
      path: '/profile/billing'
      fullPath: '/profile/billing'
      preLoaderRoute: typeof AuthenticatedProfileBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/analytics': {
      id: '/_authenticated/profile/analytics'
      path: '/profile/analytics'
      fullPath: '/profile/analytics'
      preLoaderRoute: typeof AuthenticatedProfileAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/ads/': {
      id: '/_authenticated/profile/ads/'
      path: '/profile/ads'
      fullPath: '/profile/ads/'
      preLoaderRoute: typeof AuthenticatedProfileAdsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-deal': {
      id: '/api/public/hooks/notify-deal'
      path: '/api/public/hooks/notify-deal'
      fullPath: '/api/public/hooks/notify-deal'
      preLoaderRoute: typeof ApiPublicHooksNotifyDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/config/maps': {
      id: '/api/public/config/maps'
      path: '/api/public/config/maps'
      fullPath: '/api/public/config/maps'
      preLoaderRoute: typeof ApiPublicConfigMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/ads/new': {
      id: '/_authenticated/profile/ads/new'
      path: '/profile/ads/new'
      fullPath: '/profile/ads/new'
      preLoaderRoute: typeof AuthenticatedProfileAdsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/ads/$id': {
      id: '/_authenticated/profile/ads/$id'
      path: '/profile/ads/$id'
      fullPath: '/profile/ads/$id'
      preLoaderRoute: typeof AuthenticatedProfileAdsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileAnalyticsRoute: typeof AuthenticatedProfileAnalyticsRoute
  AuthenticatedProfileBillingRoute: typeof AuthenticatedProfileBillingRoute
  AuthenticatedProfileDashboardRoute: typeof AuthenticatedProfileDashboardRoute
  AuthenticatedProfileNotificationsRoute: typeof AuthenticatedProfileNotificationsRoute
  AuthenticatedProfileSecurityRoute: typeof AuthenticatedProfileSecurityRoute
  AuthenticatedProfileStoreRoute: typeof AuthenticatedProfileStoreRoute
  AuthenticatedProfileAdsIdRoute: typeof AuthenticatedProfileAdsIdRoute
  AuthenticatedProfileAdsNewRoute: typeof AuthenticatedProfileAdsNewRoute
  AuthenticatedProfileAdsIndexRoute: typeof AuthenticatedProfileAdsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileAnalyticsRoute: AuthenticatedProfileAnalyticsRoute,
  AuthenticatedProfileBillingRoute: AuthenticatedProfileBillingRoute,
  AuthenticatedProfileDashboardRoute: AuthenticatedProfileDashboardRoute,
  AuthenticatedProfileNotificationsRoute:
    AuthenticatedProfileNotificationsRoute,
  AuthenticatedProfileSecurityRoute: AuthenticatedProfileSecurityRoute,
  AuthenticatedProfileStoreRoute: AuthenticatedProfileStoreRoute,
  AuthenticatedProfileAdsIdRoute: AuthenticatedProfileAdsIdRoute,
  AuthenticatedProfileAdsNewRoute: AuthenticatedProfileAdsNewRoute,
  AuthenticatedProfileAdsIndexRoute: AuthenticatedProfileAdsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  ForMerchantsRoute: ForMerchantsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NearbyRoute: NearbyRoute,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectRoleRoute: SelectRoleRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminTrustRoute: AdminTrustRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DealsIdRoute: DealsIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  StoresIdRoute: StoresIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  AdminNotificationsDebugRoute: AdminNotificationsDebugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicConfigMapsRoute: ApiPublicConfigMapsRoute,
  ApiPublicHooksNotifyDealRoute: ApiPublicHooksNotifyDealRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
